---
title: "ENVS-193DS_spring-2026_final"
author: Tadeh Peroomian
date: 08-06-2026
format: 
  pdf:
    toc: true
editor: source    
---

**GitHub Repository:** 
[ENVS-193DS Spring 2026 Final](http://github.com/tadehperoomian/ENVS-193DS_spring-2026_final)


```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(readxl)
library(here)


nest <- read.csv("data/nest_data_final.csv")
```


# Problem 1

## a.

In Part 1, my co-worker used logistic regression. We can tell because the goal is to predict a probability (will an Avocet use this microhabitat or not, which is a yes/no outcome) from a continuous measurement (distance to the water edge in meters). Logistic regression is the right tool when your response variable is binary like this.

In Part 2, my co-worker used a chi-square test of independence. This is because both variables being compared are categorical — bird species (Avocet, Forster's Tern, Black-necked Stilt) and habitat type (managed pond, non-tidal marsh, salt pond, tidal marsh, tidal mudflat). A chi-square test tells us whether the two categorical variables are associated with each other or not.

## b.

Part 1: American Avocets were more likely to be found in microhabitat sites that were closer to the water's edge. This suggests that how far a spot is from the water plays a role in whether or not an Avocet chooses to use it.

Part 2: The three bird species did not use the five habitat types equally. Each species tended to show up more in certain habitats than others, meaning the habitat a bird is found in is related to which species it is.

## c.

One additional variable that could be worth looking at is water depth, measured in centimeters at each survey point using a ruler or depth probe. American Avocets are wading birds that forage by sweeping their bill through shallow water, so sites that are too deep or too dry may simply not be usable for feeding, which would directly affect whether or not Avocets choose to use a given microhabitat.







